name: Python application

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy an App Engine app
      id: deploy-app
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        deliverables: app.yaml
        credentials: ${{ secrets.GCP_CREDENTIALS }}
